[package]
name = "oroswap_pcl_common"
version = "1.0.0"
edition = "2021"
description = "Common package contains math tools and utils for Oroswap PCL pairs"
license = "GPL-3.0-only"
repository = "https://github.com/oroswap/oroswap-core"
homepage = "https://www.oroswap.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
injective = ["oroswap/injective"]
sei = ["oroswap/sei"]
zigchain = ["oroswap/zigchain"] 

[dependencies]
cosmwasm-std.workspace = true
cosmwasm-schema.workspace = true
cw-storage-plus.workspace = true
cw20 = "1"
thiserror.workspace = true
oroswap.workspace = true
oroswap-factory = { path = "../../contracts/factory", version = "1.0.0", features = ["library"] }
itertools.workspace = true

[dev-dependencies]
anyhow = "1"
oroswap-test = { path = "../oroswap_test" }