[package]
name = "oroswap-test"
version = "1.1.0"
authors = ["Oroswap"]
edition = "2021"
description = "Oroswap Test used for integration testing"
license = "GPL-3.0-only"
repository = "https://github.com/oroswap/oroswap-core-core"
homepage = "https://www.oroswap.org"

[features]
default = []
injective = []
sei = []
library = []
cosmwasm_1_1 = ["cosmwasm-std/cosmwasm_1_1"]
cosmwasm_1_2 = ["cosmwasm_1_1", "cosmwasm-std/cosmwasm_1_2"]
cosmwasm_1_3 = ["cosmwasm_1_2", "cosmwasm-std/cosmwasm_1_3"]
cosmwasm_1_4 = ["cosmwasm_1_3", "cosmwasm-std/cosmwasm_1_4"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oroswap = { workspace = true }
cosmwasm-schema = "1.2.5"
cosmwasm-std = "1.2.5"
serde = "1.0"
schemars = "0.8.1"
anyhow = "1.0"
itertools = { workspace = true }
cw-utils = { workspace = true }
cw-storage-plus = { workspace = true }
osmosis-std = "0.21.0"
neutron-std = { git = "https://github.com/neutron-org/neutron-std", branch = "main" }
prost = "0.12"
sha2 = "0.10.8"

# Test-only dependencies - only available when not building for wasm32
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
oroswap-factory = { path = "../../contracts/factory" }
cw-multi-test = { git = "https://github.com/astroport-fi/cw-multi-test", branch = "feat/bank_with_send_hooks_1_0", features = ["cosmwasm_1_1"] }
cw20-base = "1.1"