[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-cpu=generic",
    "-C", "codegen-units=1",
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=--strip-all",
]

[profile.release]
opt-level = 3
lto = true
panic = "abort"
strip = true
debug = false
overflow-checks = false
codegen-units = 1

[profile.release.build-override]
opt-level = 3
debug = false 