#!/usr/bin/env bash
set -e
set -o pipefail

# ── 0) Locate script & project root ───────────────────────────────────────
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"
OUTPUT_DIR="$project_root/artifacts"
mkdir -p "$OUTPUT_DIR"

echo "🐳 Building all contracts with Docker workspace-optimizer..."
echo "   Project root: $project_root"
echo "   Output dir: $OUTPUT_DIR"

# ── 1) Build all contracts (pair contracts have zigchain as default) ─────
echo "🚀 Building all contracts..."
echo "   Pair contracts have 'zigchain' as default feature"
echo "   This automatically builds zigchain variants!"
docker run --rm -v "$project_root":/code \
  --mount type=volume,source="$(basename "$project_root")_cache",target=/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/optimizer:0.17.0

echo "✅ All contracts built successfully!"
echo "📋 Checksums automatically generated by workspace-optimizer: $OUTPUT_DIR/checksums.txt"
echo ""
echo "📊 Build Summary:"
echo "   - Output directory: $OUTPUT_DIR"
echo "   - Build method: cosmwasm/optimizer:0.17.0 (workspace-optimizer)"
echo "   - Pair contracts built with zigchain feature (default)"
echo "   - Checksums: Automatically generated by workspace-optimizer"
