[global]
log_level = "info"

[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[rest]
enabled = false
host = "127.0.0.1"
port = 3000

[telemetry]
enabled = false
host = "127.0.0.1"
port = 3001

[[chains]]
id = "localneutron-1"
type = "CosmosSdk"
rpc_addr = "http://neutron:26657"
event_source = { mode = 'pull', interval = '1s' }
grpc_addr = "http://neutron:9090"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "neutron"
key_name = "neutron_relayer"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 5000000
gas_multiplier = 1.3
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "15s"
max_block_time = "30s"
ccv_consumer_chain = true
memo_prefix = ""
sequential_batch_tx = false
trusting_period = "288000s"

[chains.trust_threshold]
numerator = "1"
denominator = "3"

[chains.gas_price]
price = 0.01
denom = "untrn"

[chains.packet_filter]
policy = "allow"
list = [
    ["*", "*"]
]

[chains.address_type]
derivation = "cosmos"

[[chains]]
id = "localterra-1"
type = "CosmosSdk"
rpc_addr = "http://terra:26657"
event_source = { mode = 'pull', interval = '1s' }
grpc_addr = "http://terra:9090"
rpc_timeout = "10s"
trusted_node = false
account_prefix = "terra"
key_name = "terra_relayer"
key_store_type = "Test"
store_prefix = "ibc"
default_gas = 100000
max_gas = 5000000
gas_multiplier = 1.3
max_msg_num = 30
max_tx_size = 180000
max_grpc_decoding_size = 33554432
clock_drift = "5s"
max_block_time = "30s"
ccv_consumer_chain = false
memo_prefix = ""
sequential_batch_tx = false
trusting_period = "345600s"

[chains.trust_threshold]
numerator = "1"
denominator = "3"

[chains.gas_price]
price = 0.015
denom = "uluna"

[chains.packet_filter]
policy = "allow"
list = [
    ["*", "*"]
]

[chains.address_type]
derivation = "cosmos"