name: Deploy Documentation

on:
  push:
    branches: [main]
    paths: ['docs/**', '.github/workflows/docs.yml']
  pull_request:
    branches: [main]
    paths: ['docs/**']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g markdownlint-cli

      - name: Lint markdown
        run: |
          # Create .markdownlint.json with relaxed rules
          echo '{
            "MD013": false,
            "MD022": false,
            "MD025": false,
            "MD031": false,
            "MD032": false,
            "MD040": false,
            "MD047": false,
            "MD009": false,
            "MD024": false,
            "MD051": false,
            "MD012": false
          }' > .markdownlint.json
          
          markdownlint docs/**/*.md --ignore node_modules

      - name: Build documentation site
        run: |
          # Create a simple documentation index
          mkdir -p _site
          
          # Copy all markdown files
          cp -r docs/* _site/
          
          # Create a simple index.html
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Oroswap Documentation</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; }
              .container { max-width: 1200px; margin: 0 auto; }
              h1 { color: #0366d6; border-bottom: 1px solid #eaecef; padding-bottom: 10px; }
              h2 { color: #24292e; margin-top: 30px; }
              h3 { color: #24292e; }
              a { color: #0366d6; text-decoration: none; }
              a:hover { text-decoration: underline; }
              code { background-color: #f6f8fa; padding: 2px 4px; border-radius: 3px; font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; }
              pre { background-color: #f6f8fa; padding: 15px; border-radius: 6px; overflow-x: auto; }
              pre code { background-color: transparent; padding: 0; }
              .nav { background-color: #f6f8fa; padding: 15px; border-radius: 6px; margin-bottom: 20px; }
              .nav ul { list-style: none; padding: 0; margin: 0; }
              .nav li { margin: 5px 0; }
              .content { background-color: white; padding: 20px; border-radius: 6px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="nav">
                <h3>Documentation</h3>
                <ul>
                  <li><a href="contracts/factory.md">Factory Contract</a></li>
                  <li><a href="contracts/pairs.md">Pair Contracts</a></li>
                  <li><a href="contracts/router.md">Router Contract</a></li>
                  <li><a href="contracts/incentives.md">Incentives Contract</a></li>
                  <li><a href="events/factory-events.md">Factory Events</a></li>
                  <li><a href="transactions/swap-examples.md">Swap Examples</a></li>
                  <li><a href="deployment/testnet.md">Testnet Deployment</a></li>
                </ul>
              </div>
              <div class="content">
                <h1>Oroswap Documentation</h1>
                <p>Welcome to the Oroswap DEX documentation! This guide will help you understand, deploy, and interact with the Oroswap decentralized exchange on Zigchain.</p>
                
                <h2>Quick Start</h2>
                <ol>
                  <li><a href="deployment/testnet.md">Deploy Contracts</a></li>
                  <li><a href="contracts/factory.md">Create Pairs</a></li>
                  <li><a href="transactions/swap-examples.md">Start Trading</a></li>
                </ol>

                <h2>Contract Addresses (Testnet v1.0.0)</h2>
                <ul>
                  <li><strong>Factory:</strong> <code>zig17a7mlm84taqmd3enrpcxhrwzclj9pga8efz83vrswnnywr8tv26s7mpq30</code></li>
                  <li><strong>Router:</strong> <code>zig1g00t6pxg3xn7vk0vt29zu9vztm3wsq5t5wegutlg94uddju0yr5sye3r3a</code></li>
                  <li><strong>Incentives:</strong> <code>zig1sq7mu45and7htxdjwe9htl0q3y33qlnt6cded6z299303pya5d0qda8sg7</code></li>
                  <li><strong>Coin Registry:</strong> <code>zig1knyre4stvestyn032u9edf9w0fxhgv4szlwdvy2f69jludmunknswaxdsr</code></li>
                </ul>

                <h2>Useful Links</h2>
                <ul>
                  <li><a href="https://github.com/oroswap/oroswap-core">GitHub Repository</a></li>
                  <li><a href="https://explorer.zigchain.com/">Zigchain Explorer</a></li>
                </ul>
              </div>
            </div>
          </body>
          </html>
          EOF

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: _site/
          retention-days: 30 